#deploy to DigitalOcean Kubernetes
# This GitHub Actions workflow deploys a Spring Boot application to DigitalOcean Kubernetes.
name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub or DOCR
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/springboot-app:latest

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/springboot-deployment springboot-container=${{ secrets.DOCKER_USERNAME }}/springboot-app:latest
