#test
name: Deploy to AKS

on:
  push:
    branches: [main]

env:
  ACR_NAME: testcontainerregistrymerzigo
  ACR_LOGIN_SERVER: testcontainerregistrymerzigo.azurecr.io
  IMAGE_NAME: merzigo-demo
  NAMESPACE: java-demoapp-namespace
  CLUSTER_NAME: testkubeclustermerzigodemo
  RESOURCE_GROUP: TestResourceGroup

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Azure Login (CLI)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}

      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: |
            .github/manifests/configmap.yaml
            .github/manifests/deployment.yaml
            .github/manifests/service.yaml
          images: |
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}
